sudo: required
services:
  - docker

before_install:
  - docker build -t qhieu45/react-test -f ./client/Dockerfile ./client --target=builder

script:
  - docker run qhieu45/react-test npm test -- --coverage

after_success:
  - docker build -t qhieu45/multi-docker-client ./client
  - docker build -t qhieu45/multi-docker-nginx ./nginx
  - docker build -t qhieu45/multi-docker-api ./api
  - docker build -t qhieu45/multi-docker-worker ./worker

  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  # Take images & push to Docker Hub
  - docker push qhieu45/multi-docker-client
  - docker push qhieu45/multi-docker-nginx
  - docker push qhieu45/multi-docker-api
  - docker push qhieu45/multi-docker-worker
